version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    install:
      - pip install --upgrade pip
      - pip install .
      - pip install --group dev

sphinx:
  configuration: docs/conf.py
