on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

name: release

permissions: {}

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For Trusted Publishing + attestations.
      contents: write # For uploading release assets.

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: false

      - name: build
        run: make dist

      - name: publish
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

