on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

name: release

permissions: {}

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For Trusted Publishing + attestations.
      contents: write # For uploading release assets.

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          enable-cache: false

      - name: build
        run: make dist

      - name: publish
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2

